// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_message_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_message_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4023000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4023004 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_message_2eproto

PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_message_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable
    descriptor_table_message_2eproto;
namespace masstree {
class Range_req;
struct Range_reqDefaultTypeInternal;
extern Range_reqDefaultTypeInternal _Range_req_default_instance_;
class Req;
struct ReqDefaultTypeInternal;
extern ReqDefaultTypeInternal _Req_default_instance_;
class Resp;
struct RespDefaultTypeInternal;
extern RespDefaultTypeInternal _Resp_default_instance_;
class Update_req;
struct Update_reqDefaultTypeInternal;
extern Update_reqDefaultTypeInternal _Update_req_default_instance_;
}  // namespace masstree
PROTOBUF_NAMESPACE_OPEN
template <>
::masstree::Range_req* Arena::CreateMaybeMessage<::masstree::Range_req>(Arena*);
template <>
::masstree::Req* Arena::CreateMaybeMessage<::masstree::Req>(Arena*);
template <>
::masstree::Resp* Arena::CreateMaybeMessage<::masstree::Resp>(Arena*);
template <>
::masstree::Update_req* Arena::CreateMaybeMessage<::masstree::Update_req>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

namespace masstree {

// ===================================================================


// -------------------------------------------------------------------

class Req final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:masstree.Req) */ {
 public:
  inline Req() : Req(nullptr) {}
  ~Req() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Req(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Req(const Req& from);
  Req(Req&& from) noexcept
    : Req() {
    *this = ::std::move(from);
  }

  inline Req& operator=(const Req& from) {
    CopyFrom(from);
    return *this;
  }
  inline Req& operator=(Req&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Req& default_instance() {
    return *internal_default_instance();
  }
  static inline const Req* internal_default_instance() {
    return reinterpret_cast<const Req*>(
               &_Req_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Req& a, Req& b) {
    a.Swap(&b);
  }
  inline void Swap(Req* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Req* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Req* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Req>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Req& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Req& from) {
    Req::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Req* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "masstree.Req";
  }
  protected:
  explicit Req(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 2,
    kReqTypeFieldNumber = 1,
  };
  // bytes key = 2;
  void clear_key() ;
  const std::string& key() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_key(Arg_&& arg, Args_... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* ptr);

  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(
      const std::string& value);
  std::string* _internal_mutable_key();

  public:
  // uint32 req_type = 1;
  void clear_req_type() ;
  ::uint32_t req_type() const;
  void set_req_type(::uint32_t value);

  private:
  ::uint32_t _internal_req_type() const;
  void _internal_set_req_type(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:masstree.Req)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    ::uint32_t req_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};// -------------------------------------------------------------------

class Range_req final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:masstree.Range_req) */ {
 public:
  inline Range_req() : Range_req(nullptr) {}
  ~Range_req() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Range_req(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Range_req(const Range_req& from);
  Range_req(Range_req&& from) noexcept
    : Range_req() {
    *this = ::std::move(from);
  }

  inline Range_req& operator=(const Range_req& from) {
    CopyFrom(from);
    return *this;
  }
  inline Range_req& operator=(Range_req&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Range_req& default_instance() {
    return *internal_default_instance();
  }
  static inline const Range_req* internal_default_instance() {
    return reinterpret_cast<const Range_req*>(
               &_Range_req_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Range_req& a, Range_req& b) {
    a.Swap(&b);
  }
  inline void Swap(Range_req* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Range_req* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Range_req* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Range_req>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Range_req& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Range_req& from) {
    Range_req::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Range_req* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "masstree.Range_req";
  }
  protected:
  explicit Range_req(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 3,
    kReqTypeFieldNumber = 1,
    kRangeFieldNumber = 2,
  };
  // bytes key = 3;
  void clear_key() ;
  const std::string& key() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_key(Arg_&& arg, Args_... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* ptr);

  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(
      const std::string& value);
  std::string* _internal_mutable_key();

  public:
  // uint32 req_type = 1;
  void clear_req_type() ;
  ::uint32_t req_type() const;
  void set_req_type(::uint32_t value);

  private:
  ::uint32_t _internal_req_type() const;
  void _internal_set_req_type(::uint32_t value);

  public:
  // uint32 range = 2;
  void clear_range() ;
  ::uint32_t range() const;
  void set_range(::uint32_t value);

  private:
  ::uint32_t _internal_range() const;
  void _internal_set_range(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:masstree.Range_req)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    ::uint32_t req_type_;
    ::uint32_t range_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};// -------------------------------------------------------------------

class Update_req final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:masstree.Update_req) */ {
 public:
  inline Update_req() : Update_req(nullptr) {}
  ~Update_req() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Update_req(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Update_req(const Update_req& from);
  Update_req(Update_req&& from) noexcept
    : Update_req() {
    *this = ::std::move(from);
  }

  inline Update_req& operator=(const Update_req& from) {
    CopyFrom(from);
    return *this;
  }
  inline Update_req& operator=(Update_req&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Update_req& default_instance() {
    return *internal_default_instance();
  }
  static inline const Update_req* internal_default_instance() {
    return reinterpret_cast<const Update_req*>(
               &_Update_req_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Update_req& a, Update_req& b) {
    a.Swap(&b);
  }
  inline void Swap(Update_req* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Update_req* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Update_req* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Update_req>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Update_req& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Update_req& from) {
    Update_req::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Update_req* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "masstree.Update_req";
  }
  protected:
  explicit Update_req(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKeyFieldNumber = 2,
    kValueFieldNumber = 3,
    kReqTypeFieldNumber = 1,
  };
  // bytes key = 2;
  void clear_key() ;
  const std::string& key() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_key(Arg_&& arg, Args_... args);
  std::string* mutable_key();
  PROTOBUF_NODISCARD std::string* release_key();
  void set_allocated_key(std::string* ptr);

  private:
  const std::string& _internal_key() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_key(
      const std::string& value);
  std::string* _internal_mutable_key();

  public:
  // bytes value = 3;
  void clear_value() ;
  const std::string& value() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_value(Arg_&& arg, Args_... args);
  std::string* mutable_value();
  PROTOBUF_NODISCARD std::string* release_value();
  void set_allocated_value(std::string* ptr);

  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(
      const std::string& value);
  std::string* _internal_mutable_value();

  public:
  // uint32 req_type = 1;
  void clear_req_type() ;
  ::uint32_t req_type() const;
  void set_req_type(::uint32_t value);

  private:
  ::uint32_t _internal_req_type() const;
  void _internal_set_req_type(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:masstree.Update_req)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr key_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
    ::uint32_t req_type_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};// -------------------------------------------------------------------

class Resp final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:masstree.Resp) */ {
 public:
  inline Resp() : Resp(nullptr) {}
  ~Resp() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Resp(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Resp(const Resp& from);
  Resp(Resp&& from) noexcept
    : Resp() {
    *this = ::std::move(from);
  }

  inline Resp& operator=(const Resp& from) {
    CopyFrom(from);
    return *this;
  }
  inline Resp& operator=(Resp&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Resp& default_instance() {
    return *internal_default_instance();
  }
  static inline const Resp* internal_default_instance() {
    return reinterpret_cast<const Resp*>(
               &_Resp_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Resp& a, Resp& b) {
    a.Swap(&b);
  }
  inline void Swap(Resp* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Resp* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Resp* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Resp>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Resp& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Resp& from) {
    Resp::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Resp* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "masstree.Resp";
  }
  protected:
  explicit Resp(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kValueFieldNumber = 4,
    kReqTypeFieldNumber = 1,
    kCountFieldNumber = 2,
    kSuccessFieldNumber = 3,
  };
  // bytes value = 4;
  void clear_value() ;
  const std::string& value() const;




  template <typename Arg_ = const std::string&, typename... Args_>
  void set_value(Arg_&& arg, Args_... args);
  std::string* mutable_value();
  PROTOBUF_NODISCARD std::string* release_value();
  void set_allocated_value(std::string* ptr);

  private:
  const std::string& _internal_value() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_value(
      const std::string& value);
  std::string* _internal_mutable_value();

  public:
  // uint32 req_type = 1;
  void clear_req_type() ;
  ::uint32_t req_type() const;
  void set_req_type(::uint32_t value);

  private:
  ::uint32_t _internal_req_type() const;
  void _internal_set_req_type(::uint32_t value);

  public:
  // uint32 count = 2;
  void clear_count() ;
  ::uint32_t count() const;
  void set_count(::uint32_t value);

  private:
  ::uint32_t _internal_count() const;
  void _internal_set_count(::uint32_t value);

  public:
  // uint32 success = 3;
  void clear_success() ;
  ::uint32_t success() const;
  void set_success(::uint32_t value);

  private:
  ::uint32_t _internal_success() const;
  void _internal_set_success(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:masstree.Resp)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr value_;
    ::uint32_t req_type_;
    ::uint32_t count_;
    ::uint32_t success_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_message_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Req

// uint32 req_type = 1;
inline void Req::clear_req_type() {
  _impl_.req_type_ = 0u;
}
inline ::uint32_t Req::req_type() const {
  // @@protoc_insertion_point(field_get:masstree.Req.req_type)
  return _internal_req_type();
}
inline void Req::set_req_type(::uint32_t value) {
  _internal_set_req_type(value);
  // @@protoc_insertion_point(field_set:masstree.Req.req_type)
}
inline ::uint32_t Req::_internal_req_type() const {
  return _impl_.req_type_;
}
inline void Req::_internal_set_req_type(::uint32_t value) {
  ;
  _impl_.req_type_ = value;
}

// bytes key = 2;
inline void Req::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& Req::key() const {
  // @@protoc_insertion_point(field_get:masstree.Req.key)
  return _internal_key();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Req::set_key(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.key_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:masstree.Req.key)
}
inline std::string* Req::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:masstree.Req.key)
  return _s;
}
inline const std::string& Req::_internal_key() const {
  return _impl_.key_.Get();
}
inline void Req::_internal_set_key(const std::string& value) {
  ;


  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* Req::_internal_mutable_key() {
  ;
  return _impl_.key_.Mutable( GetArenaForAllocation());
}
inline std::string* Req::release_key() {
  // @@protoc_insertion_point(field_release:masstree.Req.key)
  return _impl_.key_.Release();
}
inline void Req::set_allocated_key(std::string* value) {
  _impl_.key_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.key_.IsDefault()) {
          _impl_.key_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:masstree.Req.key)
}

// -------------------------------------------------------------------

// Range_req

// uint32 req_type = 1;
inline void Range_req::clear_req_type() {
  _impl_.req_type_ = 0u;
}
inline ::uint32_t Range_req::req_type() const {
  // @@protoc_insertion_point(field_get:masstree.Range_req.req_type)
  return _internal_req_type();
}
inline void Range_req::set_req_type(::uint32_t value) {
  _internal_set_req_type(value);
  // @@protoc_insertion_point(field_set:masstree.Range_req.req_type)
}
inline ::uint32_t Range_req::_internal_req_type() const {
  return _impl_.req_type_;
}
inline void Range_req::_internal_set_req_type(::uint32_t value) {
  ;
  _impl_.req_type_ = value;
}

// uint32 range = 2;
inline void Range_req::clear_range() {
  _impl_.range_ = 0u;
}
inline ::uint32_t Range_req::range() const {
  // @@protoc_insertion_point(field_get:masstree.Range_req.range)
  return _internal_range();
}
inline void Range_req::set_range(::uint32_t value) {
  _internal_set_range(value);
  // @@protoc_insertion_point(field_set:masstree.Range_req.range)
}
inline ::uint32_t Range_req::_internal_range() const {
  return _impl_.range_;
}
inline void Range_req::_internal_set_range(::uint32_t value) {
  ;
  _impl_.range_ = value;
}

// bytes key = 3;
inline void Range_req::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& Range_req::key() const {
  // @@protoc_insertion_point(field_get:masstree.Range_req.key)
  return _internal_key();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Range_req::set_key(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.key_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:masstree.Range_req.key)
}
inline std::string* Range_req::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:masstree.Range_req.key)
  return _s;
}
inline const std::string& Range_req::_internal_key() const {
  return _impl_.key_.Get();
}
inline void Range_req::_internal_set_key(const std::string& value) {
  ;


  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* Range_req::_internal_mutable_key() {
  ;
  return _impl_.key_.Mutable( GetArenaForAllocation());
}
inline std::string* Range_req::release_key() {
  // @@protoc_insertion_point(field_release:masstree.Range_req.key)
  return _impl_.key_.Release();
}
inline void Range_req::set_allocated_key(std::string* value) {
  _impl_.key_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.key_.IsDefault()) {
          _impl_.key_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:masstree.Range_req.key)
}

// -------------------------------------------------------------------

// Update_req

// uint32 req_type = 1;
inline void Update_req::clear_req_type() {
  _impl_.req_type_ = 0u;
}
inline ::uint32_t Update_req::req_type() const {
  // @@protoc_insertion_point(field_get:masstree.Update_req.req_type)
  return _internal_req_type();
}
inline void Update_req::set_req_type(::uint32_t value) {
  _internal_set_req_type(value);
  // @@protoc_insertion_point(field_set:masstree.Update_req.req_type)
}
inline ::uint32_t Update_req::_internal_req_type() const {
  return _impl_.req_type_;
}
inline void Update_req::_internal_set_req_type(::uint32_t value) {
  ;
  _impl_.req_type_ = value;
}

// bytes key = 2;
inline void Update_req::clear_key() {
  _impl_.key_.ClearToEmpty();
}
inline const std::string& Update_req::key() const {
  // @@protoc_insertion_point(field_get:masstree.Update_req.key)
  return _internal_key();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Update_req::set_key(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.key_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:masstree.Update_req.key)
}
inline std::string* Update_req::mutable_key() {
  std::string* _s = _internal_mutable_key();
  // @@protoc_insertion_point(field_mutable:masstree.Update_req.key)
  return _s;
}
inline const std::string& Update_req::_internal_key() const {
  return _impl_.key_.Get();
}
inline void Update_req::_internal_set_key(const std::string& value) {
  ;


  _impl_.key_.Set(value, GetArenaForAllocation());
}
inline std::string* Update_req::_internal_mutable_key() {
  ;
  return _impl_.key_.Mutable( GetArenaForAllocation());
}
inline std::string* Update_req::release_key() {
  // @@protoc_insertion_point(field_release:masstree.Update_req.key)
  return _impl_.key_.Release();
}
inline void Update_req::set_allocated_key(std::string* value) {
  _impl_.key_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.key_.IsDefault()) {
          _impl_.key_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:masstree.Update_req.key)
}

// bytes value = 3;
inline void Update_req::clear_value() {
  _impl_.value_.ClearToEmpty();
}
inline const std::string& Update_req::value() const {
  // @@protoc_insertion_point(field_get:masstree.Update_req.value)
  return _internal_value();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Update_req::set_value(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.value_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:masstree.Update_req.value)
}
inline std::string* Update_req::mutable_value() {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:masstree.Update_req.value)
  return _s;
}
inline const std::string& Update_req::_internal_value() const {
  return _impl_.value_.Get();
}
inline void Update_req::_internal_set_value(const std::string& value) {
  ;


  _impl_.value_.Set(value, GetArenaForAllocation());
}
inline std::string* Update_req::_internal_mutable_value() {
  ;
  return _impl_.value_.Mutable( GetArenaForAllocation());
}
inline std::string* Update_req::release_value() {
  // @@protoc_insertion_point(field_release:masstree.Update_req.value)
  return _impl_.value_.Release();
}
inline void Update_req::set_allocated_value(std::string* value) {
  _impl_.value_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.value_.IsDefault()) {
          _impl_.value_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:masstree.Update_req.value)
}

// -------------------------------------------------------------------

// Resp

// uint32 req_type = 1;
inline void Resp::clear_req_type() {
  _impl_.req_type_ = 0u;
}
inline ::uint32_t Resp::req_type() const {
  // @@protoc_insertion_point(field_get:masstree.Resp.req_type)
  return _internal_req_type();
}
inline void Resp::set_req_type(::uint32_t value) {
  _internal_set_req_type(value);
  // @@protoc_insertion_point(field_set:masstree.Resp.req_type)
}
inline ::uint32_t Resp::_internal_req_type() const {
  return _impl_.req_type_;
}
inline void Resp::_internal_set_req_type(::uint32_t value) {
  ;
  _impl_.req_type_ = value;
}

// uint32 count = 2;
inline void Resp::clear_count() {
  _impl_.count_ = 0u;
}
inline ::uint32_t Resp::count() const {
  // @@protoc_insertion_point(field_get:masstree.Resp.count)
  return _internal_count();
}
inline void Resp::set_count(::uint32_t value) {
  _internal_set_count(value);
  // @@protoc_insertion_point(field_set:masstree.Resp.count)
}
inline ::uint32_t Resp::_internal_count() const {
  return _impl_.count_;
}
inline void Resp::_internal_set_count(::uint32_t value) {
  ;
  _impl_.count_ = value;
}

// uint32 success = 3;
inline void Resp::clear_success() {
  _impl_.success_ = 0u;
}
inline ::uint32_t Resp::success() const {
  // @@protoc_insertion_point(field_get:masstree.Resp.success)
  return _internal_success();
}
inline void Resp::set_success(::uint32_t value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:masstree.Resp.success)
}
inline ::uint32_t Resp::_internal_success() const {
  return _impl_.success_;
}
inline void Resp::_internal_set_success(::uint32_t value) {
  ;
  _impl_.success_ = value;
}

// bytes value = 4;
inline void Resp::clear_value() {
  _impl_.value_.ClearToEmpty();
}
inline const std::string& Resp::value() const {
  // @@protoc_insertion_point(field_get:masstree.Resp.value)
  return _internal_value();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Resp::set_value(Arg_&& arg,
                                                     Args_... args) {
  ;
  _impl_.value_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:masstree.Resp.value)
}
inline std::string* Resp::mutable_value() {
  std::string* _s = _internal_mutable_value();
  // @@protoc_insertion_point(field_mutable:masstree.Resp.value)
  return _s;
}
inline const std::string& Resp::_internal_value() const {
  return _impl_.value_.Get();
}
inline void Resp::_internal_set_value(const std::string& value) {
  ;


  _impl_.value_.Set(value, GetArenaForAllocation());
}
inline std::string* Resp::_internal_mutable_value() {
  ;
  return _impl_.value_.Mutable( GetArenaForAllocation());
}
inline std::string* Resp::release_value() {
  // @@protoc_insertion_point(field_release:masstree.Resp.value)
  return _impl_.value_.Release();
}
inline void Resp::set_allocated_value(std::string* value) {
  _impl_.value_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.value_.IsDefault()) {
          _impl_.value_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:masstree.Resp.value)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace masstree


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_message_2eproto_2epb_2eh
